# Generated by Django 5.2.5 on 2025-11-07 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('headshot_url', models.URLField(help_text='URL to your headshot image')),
                ('bio', models.TextField()),
                ('interests', models.CharField(help_text='Comma-separated list of interests', max_length=255)),
                ('inspiration', models.TextField()),
                ('career_highlights', models.TextField(help_text='List your career highlights, one per line.')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(help_text='The full content of the blog post.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(help_text='Comma-separated list of tags', max_length=255)),
                ('view_count', models.IntegerField(default=0)),
                ('meta_description', models.CharField(max_length=160)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('preferred_contact_method', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GithubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('last_sync', models.DateTimeField()),
                ('total_repos', models.IntegerField()),
                ('public_repos', models.IntegerField()),
                ('private_repos', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(help_text="e.g., 'Programming Language', 'Framework', 'Tool'", max_length=100)),
                ('proficiency_level', models.CharField(help_text="e.g., 'Beginner', 'Intermediate', 'Advanced', 'Expert'", max_length=50)),
                ('rating_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='A score from 1 to 5')),
                ('years_of_experience', models.IntegerField()),
                ('is_key_skill', models.BooleanField(default=False)),
                ('icon_name', models.CharField(blank=True, help_text="e.g., 'devicon-python-plain'", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('source', models.CharField(help_text='Name of the person giving the testimonial', max_length=100)),
                ('title', models.CharField(help_text="Job title of the source, e.g., 'CEO at ExampleCorp'", max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('years', models.CharField(help_text="e.g., '2018 - 2020'", max_length=20)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='Portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='Portfolio.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text="e.g., 'fab fa-linkedin'", max_length=50, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='Portfolio.about')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('description', models.TextField()),
                ('problem_solved', models.TextField()),
                ('my_role', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Ongoing', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('repo_link', models.URLField(blank=True, null=True)),
                ('deployment_status', models.CharField(default='In Development', max_length=50)),
                ('hosting_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('test_coverage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage, e.g., 85.50', max_digits=5, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='projects', to='Portfolio.category')),
                ('technologies', models.ManyToManyField(related_name='projects', to='Portfolio.technology')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('years', models.CharField(help_text="e.g., '2022 - Present'", max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('responsibilities', models.TextField(help_text='List of responsibilities, one per line.')),
                ('tech_stack', models.CharField(help_text='Comma-separated list of technologies', max_length=255)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='Portfolio.about')),
            ],
        ),
    ]
